name: ShellCheck Lint                                   # Define the name of the workflow

on: [push, pull_request]                                # Trigger the workflow on push and pull request events

jobs:                                                   # Initialise jobs
  lint:                                                 # Define a job named 'lint'
    runs-on: ubuntu-latest                              # Specifies the type of VM to provision

    container:                                          # Initialise container
      image: monkeyknuckles/shellcheck                  # Points to Shellcheck container

    steps:                                              # List of steps to execute
      - name: Checkout code                             # Checkout code label text
        uses: actions/checkout@v3                       # Use the checkout action to clone the repository

      - name: Copy ShellCheck configuration             # Set ShellCheck configuration file label text
        run: cp /app/.shellcheckrc $GITHUB_WORKSPACE    # Include the ShellCheck configuration file in the docker build

      - name: Run Lint ShellCheck                       # Set lint ShellCheck label text
        run: |                                          # Lint all ShellScript files
             find . -name "*.sh" -exec \
             shellcheck --source-path=SOURCEPATHS \
             .shellcheckrc --color {} +
             
             
      